// features/inventory/services/mockData.js

export const productsMock = [
  {
    id: 1,
    code: 'BRK-1001',
    barcode: '6260000000001',
    name: 'لنت ترمز جلو',
    brand: 'بوش',
    category: 'سیستم ترمز',
    unit: 'دست',
    purchasePrice: 350000,
    retailPrice: 450000,
    wholesalePrice: 420000,
    tax: 9,
    stock: 45,
    compatibleCars: ['پژو ۲۰۶', 'پژو پارس', 'سمند'],
    imageUrl: '', // آدرس عکس در صورت وجود
  },
  {
    id: 2,
    code: 'FLT-2022',
    barcode: '6260000000002',
    name: 'فیلتر روغن',
    brand: 'مان',
    category: 'موتور',
    unit: 'عدد',
    purchasePrice: 90000,
    retailPrice: 120000,
    wholesalePrice: 105000,
    tax: 9,
    stock: 120,
    compatibleCars: ['پراید', 'تیبا', 'ساینا'],
    imageUrl: '',
  },
  {
    id: 3,
    code: 'SHK-305',
    barcode: '6260000000003',
    name: 'کمک فنر جلو',
    brand: 'ساکس',
    category: 'سیستم تعلیق',
    unit: 'عدد',
    purchasePrice: 1500000,
    retailPrice: 1850000,
    wholesalePrice: 1700000,
    tax: 9,
    stock: 8,
    compatibleCars: ['تویوتا کرولا', 'هیوندای النترا'],
    imageUrl: '',
  },
  {
    id: 4,
    code: 'LMP-98H',
    barcode: '6260000000004',
    name: 'لامپ هدلایت H4',
    brand: 'فیلیپس',
    category: 'برق و روشنایی',
    unit: 'جفت',
    purchasePrice: 65000,
    retailPrice: 89000,
    wholesalePrice: 75000,
    tax: 0,
    stock: 0,
    compatibleCars: ['اکثر خودروها'],
    imageUrl: '',
  },
  {
    id: 5,
    code: 'BTY-755',
    barcode: '6260000000005',
    name: 'باتری ۶۰ آمپر',
    brand: 'سپاهان باتری',
    category: 'برق و روشنایی',
    unit: 'عدد',
    purchasePrice: 2800000,
    retailPrice: 3250000,
    wholesalePrice: 3100000,
    tax: 9,
    stock: 15,
    compatibleCars: ['پژو ۴۰۵', 'سمند', 'دنا'],
    imageUrl: '',
  },
  {
    id: 6,
    code: 'BRK-220',
    barcode: '6260000000006',
    name: 'کاسه چرخ عقب',
    brand: 'لنکر',
    category: 'سیستم ترمز',
    unit: 'عدد',
    purchasePrice: 550000,
    retailPrice: 680000,
    wholesalePrice: 620000,
    tax: 9,
    stock: 22,
    compatibleCars: ['پراید ۱۱۱', 'تیبا ۲'],
    imageUrl: '',
  },
  {
    id: 7,
    code: 'FLT-415',
    barcode: '6260000000007',
    name: 'فیلتر هوای موتور',
    brand: 'تویس',
    category: 'موتور',
    unit: 'عدد',
    purchasePrice: 70000,
    retailPrice: 95000,
    wholesalePrice: 85000,
    tax: 9,
    stock: 60,
    compatibleCars: ['پژو ۲۰۶', '۲۰۷', '۳۰۵'],
    imageUrl: '',
  },
  {
    id: 8,
    code: 'SHK-190',
    barcode: '6260000000008',
    name: 'کمک فنر عقب',
    brand: 'مونرو',
    category: 'سیستم تعلیق',
    unit: 'عدد',
    purchasePrice: 1100000,
    retailPrice: 1420000,
    wholesalePrice: 1300000,
    tax: 9,
    stock: 3,
    compatibleCars: ['رنو ساندرو', 'مگان'],
    imageUrl: '',
  },
  {
    id: 9,
    code: 'BRG-006',
    barcode: '6260000000009',
    name: 'یاتاقان شاتون',
    brand: 'ماله',
    category: 'موتور',
    unit: 'دست',
    purchasePrice: 700000,
    retailPrice: 890000,
    wholesalePrice: 800000,
    tax: 9,
    stock: 0,
    compatibleCars: ['پژو ۴۰۵', 'سمند'],
    imageUrl: '',
  },
  {
    id: 10,
    code: 'CLT-884',
    barcode: '6260000000010',
    name: 'کلاچ کامل',
    brand: 'لوك',
    category: 'گیربکس',
    unit: 'کیت',
    purchasePrice: 2200000,
    retailPrice: 2750000,
    wholesalePrice: 2500000,
    tax: 9,
    stock: 5,
    compatibleCars: ['پژو ۲۰۶', 'پارس'],
    imageUrl: '',
  }
];

const generateMoreProducts = (count) => {
  const brands = ['بوش', 'مان', 'ساکس', 'لنکر', 'تویس', 'ماله', 'دنسو', 'میتسوبیشی'];
  const categories = ['موتور', 'سیستم ترمز', 'سیستم تعلیق', 'برق و روشنایی', 'بدنه', 'گیربکس', 'سیستم خنک کننده'];
  const cars = ['پژو ۲۰۶', 'پراید', 'تویوتا کرولا', 'هیوندای سانتافه', 'رنو ساندرو', 'کیا سراتو'];
  const units = ['عدد', 'بسته', 'دست', 'جفت', 'کیت'];
  
  const products = [...productsMock];
  
  for (let i = productsMock.length + 1; i <= count; i++) {
    const retailPrice = 100000 + (i * 25000);
    const purchasePrice = retailPrice * 0.75; // فرض: قیمت خرید ۲۵٪ کمتر از فروش است
    const wholesalePrice = retailPrice * 0.90; // فرض: قیمت عمده ۱۰٪ کمتر از فروش است

    products.push({
      id: i,
      code: `MOCK-${i}`,
      barcode: `6260000000${String(i).padStart(3, '0')}`,
      name: `قطعه نمونه ${i}`,
      brand: brands[i % brands.length],
      category: categories[i % categories.length],
      unit: units[i % units.length],
      purchasePrice: purchasePrice,
      retailPrice: retailPrice,
      wholesalePrice: wholesalePrice,
      tax: 9,
      stock: Math.floor(Math.random() * 100),
      compatibleCars: [cars[i % cars.length], cars[(i+2) % cars.length]],
      imageUrl: '',
    });
  }
  return products;
};

export const allProducts = generateMoreProducts(50);
