// features/inventory/services/mockData.js

export const productsMock = [
  {
    id: 1,
    sku: 'BRK-1001',
    name: 'لنت ترمز جلو',
    brand: 'بوش',
    category: 'سیستم ترمز',
    price: 450000,
    stock: 45,
    compatibleCars: ['پژو ۲۰۶', 'پژو پارس', 'سمند'],
  },
  {
    id: 2,
    sku: 'FLT-2022',
    name: 'فیلتر روغن',
    brand: 'مان',
    category: 'موتور',
    price: 120000,
    stock: 120,
    compatibleCars: ['پراید', 'تیبا', 'ساینا'],
  },
  {
    id: 3,
    sku: 'SHK-305',
    name: 'کمک فنر جلو',
    brand: 'ساکس',
    category: 'سیستم تعلیق',
    price: 1850000,
    stock: 8,
    compatibleCars: ['تویوتا کرولا', 'هیوندای النترا'],
  },
  {
    id: 4,
    sku: 'LMP-98H',
    name: 'لامپ هدلایت H4',
    brand: 'فیلیپس',
    category: 'برق و روشنایی',
    price: 89000,
    stock: 0,
    compatibleCars: ['اکثر خودروها'],
  },
  {
    id: 5,
    sku: 'BTY-755',
    name: 'باتری ۶۰ آمپر',
    brand: 'سپاهان باتری',
    category: 'برق و روشنایی',
    price: 3250000,
    stock: 15,
    compatibleCars: ['پژو ۴۰۵', 'سمند', 'دنا'],
  },
  {
    id: 6,
    sku: 'BRK-220',
    name: 'کاسه چرخ عقب',
    brand: 'لنکر',
    category: 'سیستم ترمز',
    price: 680000,
    stock: 22,
    compatibleCars: ['پراید ۱۱۱', 'تیبا ۲'],
  },
  {
    id: 7,
    sku: 'FLT-415',
    name: 'فیلتر هوای موتور',
    brand: 'تویس',
    category: 'موتور',
    price: 95000,
    stock: 60,
    compatibleCars: ['پژو ۲۰۶', '۲۰۷', '۳۰۵'],
  },
  {
    id: 8,
    sku: 'SHK-190',
    name: 'کمک فنر عقب',
    brand: 'مونرو',
    category: 'سیستم تعلیق',
    price: 1420000,
    stock: 3,
    compatibleCars: ['رنو ساندرو', 'مگان'],
  },
  {
    id: 9,
    sku: 'BRG-006',
    name: 'یاتاقان شاتون',
    brand: 'ماله',
    category: 'موتور',
    price: 890000,
    stock: 0,
    compatibleCars: ['پژو ۴۰۵', 'سمند'],
  },
  {
    id: 10,
    sku: 'CLT-884',
    name: 'کلاچ کامل',
    brand: 'لوك',
    category: 'گیربکس',
    price: 2750000,
    stock: 5,
    compatibleCars: ['پژو ۲۰۶', 'پارس'],
  },
  {
    id: 11,
    sku: 'GLW-321',
    name: 'شیشه بالابر برقی',
    brand: 'اصلی',
    category: 'بدنه',
    price: 430000,
    stock: 18,
    compatibleCars: ['تیبا', 'ساینا', 'کوییک'],
  },
  {
    id: 12,
    sku: 'RAD-471',
    name: 'رادیاتور',
    brand: 'ویدا',
    category: 'سیستم خنک کننده',
    price: 1980000,
    stock: 7,
    compatibleCars: ['پژو ۴۰۵', 'سمند سورن'],
  },
  {
    id: 13,
    sku: 'PNL-002',
    name: 'پنل درب راننده',
    brand: 'سایپا',
    category: 'بدنه',
    price: 560000,
    stock: 4,
    compatibleCars: ['پراید ۱۳۱'],
  },
  {
    id: 14,
    sku: 'SEN-987',
    name: 'سنسور اکسیژن',
    brand: 'بوش',
    category: 'برق و الکترونیک',
    price: 1340000,
    stock: 11,
    compatibleCars: ['تویوتا کمری', 'هوندا سیویک'],
  },
  {
    id: 15,
    sku: 'ALT-554',
    name: 'دینام',
    brand: 'دنسو',
    category: 'برق و روشنایی',
    price: 3250000,
    stock: 0,
    compatibleCars: ['مزدا ۳', 'تویوتا کرولا'],
  },
  {
    id: 16,
    sku: 'GKT-712',
    name: 'واشر سرسیلندر',
    brand: 'الرینگ',
    category: 'موتور',
    price: 210000,
    stock: 30,
    compatibleCars: ['پژو ۲۰۶', 'پارس'],
  },
  {
    id: 17,
    sku: 'HOS-451',
    name: 'شلنگ رادیاتور',
    brand: 'قطعه گستر',
    category: 'سیستم خنک کننده',
    price: 82000,
    stock: 55,
    compatibleCars: ['پراید', 'تیبا'],
  },
  {
    id: 18,
    sku: 'WPM-888',
    name: 'پمپ آب',
    brand: 'میتسوبیشی',
    category: 'سیستم خنک کننده',
    price: 970000,
    stock: 9,
    compatibleCars: ['تویوتا لندکروز'],
  },
  {
    id: 19,
    sku: 'BRK-402',
    name: 'ديسک ترمز',
    brand: 'برمبو',
    category: 'سیستم ترمز',
    price: 2340000,
    stock: 2,
    compatibleCars: ['بی‌ام‌و سری ۳', 'مرسدس C200'],
  },
  {
    id: 20,
    sku: 'LMP-560',
    name: 'مه شکن جلو',
    brand: 'هالا',
    category: 'برق و روشنایی',
    price: 325000,
    stock: 14,
    compatibleCars: ['دنا', 'رانا', 'کوییک'],
  },
];

// در صورت نیاز می‌توانید تعداد بیشتری آیتم بسازید (تکرار با id متفاوت)
// برای مثال، تا ۵۰ آیتم با استفاده از حلقه تولید کنید
const generateMoreProducts = (count) => {
  const brands = ['بوش', 'مان', 'ساکس', 'لنکر', 'تویس', 'ماله', 'دنسو', 'میتسوبیشی'];
  const categories = ['موتور', 'سیستم ترمز', 'سیستم تعلیق', 'برق و روشنایی', 'بدنه', 'گیربکس', 'سیستم خنک کننده'];
  const cars = ['پژو ۲۰۶', 'پراید', 'تویوتا کرولا', 'هیوندای سانتافه', 'رنو ساندرو', 'کیا سراتو'];
  const products = [...productsMock];
  for (let i = productsMock.length + 1; i <= count; i++) {
    products.push({
      id: i,
      sku: `MOCK-${i}`,
      name: `قطعه نمونه ${i}`,
      brand: brands[i % brands.length],
      category: categories[i % categories.length],
      price: 100000 + (i * 25000),
      stock: Math.floor(Math.random() * 100),
      compatibleCars: [cars[i % cars.length], cars[(i+2) % cars.length]],
    });
  }
  return products;
};

// اگر تعداد محصولات ۲۰ عدد کافی نیست، می‌توانید تعداد را مثلاً به ۵۰ برسانید
export const allProducts = generateMoreProducts(50);