import { ROUTES } from "./routes";

import {
  BarChart3,
  Barcode,
  BookOpen,
  Box,
  Building2,
  ClipboardList,
  FilePlus,
  FileText,
  HelpCircle,
  Home,
  Info,
  List,
  PlusCircle,
  RotateCcw,
  Shield,
  ShoppingCart,
  Store,
  Tags,
  Truck,
  UserCog,
  Users,
  Warehouse,
} from "lucide-react";

export const navigationData = {
  // فقط *ساختارِ* منو. هویتِ کاربر و واحد/تیمِ او اینجا نیست: صفتِ خودِ
  // اوست در بکند (`User.DepartmentId`/`User.TeamId`) و سایدبار آن را از
  // `useSessionQuery` می‌گیرد.
  navMain: [
    {
      title: "داشبورد",
      url: ROUTES.DASHBOARD,
      icon: Home,
      isActive: false,
      permission: "dashboard",
      items: [],
    },
    {
      title: "تامین کنندگان",
      url: ROUTES.SUPPLIERS,
      icon: Truck,
      isActive: false,
      permission: "suppliers",
      items: [
        {
          title: "لیست تامین کنندگان",
          url: ROUTES.SUPPLIERS_LIST,
          permission: "suppliers_view",
          icon: List,
          description: "مشاهده و جستجوی تامین کنندگان",
        },
        {
          title: "اضافه کردن تامین کننده",
          url: ROUTES.SUPPLIERS_NEW,
          permission: "suppliers_create",
          icon: PlusCircle,
          description: "ثبت تامین کننده جدید",
        },
      ],
    },
    {
      title: "مشتریان",
      url: ROUTES.CUSTOMERS,
      icon: Users,
      isActive: false,
      permission: "customers",
      items: [
        {
          title: "لیست مشتریان",
          url: ROUTES.CUSTOMERS_LIST,
          permission: "customers_view",
          icon: List,
          description: "مشاهده و جستجوی مشتریان",
        },
        {
          title: "اضافه کردن مشتری جدید",
          url: ROUTES.CUSTOMERS_NEW,
          permission: "customers_create",
          icon: PlusCircle,
          description: "ثبت مشتری جدید",
        },
      ],
    },
    {
      title: "کارمندان",
      url: ROUTES.EMPLOYEES,
      icon: UserCog,
      isActive: false,
      // فقط ادمین — وقتی لایه‌ی سطح دسترسی آماده شد، این permission باید
      // تنها به نقش «مدیر سیستم» داده شود.
      permission: "employees",
      items: [
        {
          title: "لیست کارمندان",
          url: ROUTES.EMPLOYEES_LIST,
          permission: "employees_view",
          icon: List,
          description: "مشاهده و جستجوی کاربران سیستم",
        },
        {
          title: "افزودن کارمند جدید",
          url: ROUTES.EMPLOYEES_NEW,
          permission: "employees_create",
          icon: PlusCircle,
          description: "ثبت کارمند و ساخت حساب کاربری",
        },
      ],
    },
    {
      title: "ساختار سازمانی",
      url: ROUTES.ORGANIZATION,
      icon: Building2,
      isActive: false,
      // فقط ادمین — همراه با «کارمندان».
      permission: "organization",
      items: [
        {
          title: "واحدهای سازمانی",
          url: ROUTES.ORG_DEPARTMENTS,
          permission: "organization_view",
          icon: Building2,
          description: "تعریف واحدها و تعیین مدیر هر واحد",
        },
        {
          title: "تیم‌ها",
          url: ROUTES.ORG_TEAMS,
          permission: "organization_view",
          icon: Users,
          description: "تعریف تیم‌های هر واحد و تعیین مدیر تیم",
        },
      ],
    },
    {
      title: "انبار",
      url: ROUTES.WAREHOUSE,
      icon: Warehouse,
      isActive: false,
      permission: "warehouse",
      items: [
        {
          title: "لیست کالاها",
          url: ROUTES.WAREHOUSE_PRODUCTS,
          permission: "warehouse_view",
          icon: Box,
          description: "مشاهده و جستجوی کالاها",
        },
        {
          title: "دسته‌بندی کالاها",
          url: ROUTES.WAREHOUSE_CATEGORIES,
          permission: "warehouse_view",
          icon: Tags,
          description: "ایجاد، ویرایش و حذف دسته‌بندی‌های کالا",
        },
        {
          title: "تعریف کالای جدید",
          url: ROUTES.WAREHOUSE_PRODUCTS_NEW,
          permission: "warehouse_create",
          icon: PlusCircle,
          description: "ثبت کالای جدید",
        },
        {
          title: "دریافت کالا",
          url: ROUTES.WAREHOUSE_RECEIVING,
          permission: "warehouse_receiving",
          icon: ClipboardList,
          description: "مشاهده و تأیید کالاهای دریافتی",
        },
        {
          title: "ارسال کالا",
          url: ROUTES.WAREHOUSE_SHIPPING,
          permission: "warehouse_shipping",
          icon: ClipboardList,
          description: "مشاهده و تأیید کالاهای ارسالی",
        },
        {
          title: "برچسب کالاها",
          url: ROUTES.WAREHOUSE_UNIT_LABELS,
          permission: "warehouse_receiving",
          icon: Barcode,
          description: "ساخت و چاپ بارکد تک‌تک اقلام فیزیکی",
        },
      ],
    },
    {
      title: "خرید",
      url: ROUTES.PURCHASES,
      icon: ShoppingCart,
      isActive: false,
      permission: "purchases",
      items: [
        {
          title: "لیست خرید ها",
          url: ROUTES.PURCHASES,
          permission: "purchases_create",
          icon: FilePlus,
          description: "لیست خرید های ثبت شده",
        },
        {
          title: "ثبت خرید جدید",
          url: ROUTES.PURCHASES_NEW,
          permission: "purchases_create",
          icon: FilePlus,
          description: "ثبت فاکتور خرید جدید",
        },
        {
          title: "ثبت مرجوعی به تامین‌کننده",
          url: ROUTES.PURCHASES_RETURNS_NEW,
          permission: "purchases_returns",
          icon: RotateCcw,
          description: "ثبت مرجوعی کالا به تامین‌کننده",
        },
        {
          title: "لیست مرجوعی‌ها",
          url: ROUTES.PURCHASES_RETURNS_LIST,
          permission: "purchases_returns",
          icon: List,
          description: "مشاهده لیست مرجوعی‌ها",
        },
      ],
    },
    {
      title: "فروش",
      url: ROUTES.SALES,
      icon: Store,
      isActive: false,
      permission: "sales",
      items: [
        {
          title: "لیست فروش ها",
          url: ROUTES.SALES,
          permission: "purchases_create",
          icon: FilePlus,
          description: "لیست فروش های ثبت شده",
        },
        {
          title: "ثبت فروش جدید",
          url: ROUTES.SALES_NEW,
          permission: "sales_create",
          icon: FilePlus,
          description: "ثبت فاکتور فروش جدید",
        },
        {
          title: "ثبت مرجوعی از مشتری",
          url: ROUTES.SALES_RETURNS_NEW,
          permission: "sales_returns",
          icon: RotateCcw,
          description: "ثبت مرجوعی کالا از مشتری",
        },
        {
          title: "لیست مرجوعی‌ها",
          url: ROUTES.SALES_RETURNS_LIST,
          permission: "sales_returns",
          icon: List,
          description: "مشاهده لیست مرجوعی‌ها",
        },
      ],
    },
    {
      title: "گزارش‌ها",
      url: ROUTES.REPORTS,
      icon: BarChart3,
      isActive: false,
      permission: "reports",
      items: [
        {
          title: "فعالیت کارمندان",
          url: ROUTES.REPORTS_EMPLOYEES,
          permission: "reports_view",
          icon: UserCog,
          description: "رتبه‌بندی کارمندان بر اساس فروش و خرید ثبت‌شده",
        },
        {
          title: "آمار خرید مشتریان",
          url: ROUTES.REPORTS_CUSTOMERS,
          permission: "reports_view",
          icon: Users,
          description: "پرخریدترین مشتریان و مانده‌ی تسویه‌نشده",
        },
        {
          title: "آمار خرید از تامین‌کنندگان",
          url: ROUTES.REPORTS_SUPPLIERS,
          permission: "reports_view",
          icon: Truck,
          description: "خرید از هر تامین‌کننده و وضعیت پرداخت",
        },
      ],
    },
  ],
  navSecondary: [
    {
      title: "پشتیبانی",
      // url: ROUTES.FEEDBACK,
      icon: HelpCircle,
      permission: "support",
      description: "ارسال بازخورد و گزارش مشکل",
    },
    {
      title: "مستندات",
      // url: "/docs",
      icon: BookOpen,
      permission: "all",
      description: "مستندات و راهنما",
    },
  ],
  tools: [
  ],
  footerLinks: [
    {
      title: "راهنما",
      url: "/help",
      icon: HelpCircle,
    },
    {
      title: "قوانین",
      url: "/terms",
      icon: FileText,
    },
    {
      title: "حریم خصوصی",
      url: "/privacy",
      icon: Shield,
    },
    {
      title: "درباره ما",
      url: "/about",
      icon: Info,
    },
  ],
};
